version: '3.7'

services:

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=mw-it-test
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build: ./docker/app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
    user: "${UID:-1000}:${GID:-1000}"
    restart: always

volumes:
  db_data:
